### ISSUE TITLE
Utestengte brukere telles fortsatt på statistikken over mest penger/rank

### ISSUE THREAD

**Issue by tofte96** [LarsFredrikHolstTry/mafioso-issues#61]
Se bilde: 

Utestengte brukere telles fortsatt på statistikken

**Comment by tofte96** [comment]
![Image](https://github.com/user-attachments/assets/e998cf3c-6171-467b-be94-115addb747ac)

**Comment by LarsFredrikHolstTry** [comment]
Mistenker at dette er et issue hvor cron jobs ikke kjører på dev
